name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v4
    - working-directory: ./functions
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag computercraft-streaming-music:$(date +%s)
